-- Auto-generated by tools/fetch_pro_picks.py
-- Re-run the script to refresh with latest pro match data.

local M = {}

M.PRO_PICKS_BY_POS = {
    [1] = {  -- Carries (safe lane)
        npc_dota_hero_luna                                   = true,  -- 12 picks
        npc_dota_hero_life_stealer                           = true,  -- 8 picks
        npc_dota_hero_lone_druid                             = true,  -- 6 picks
        npc_dota_hero_tiny                                   = true,  -- 6 picks
        npc_dota_hero_nevermore                              = true,  -- 6 picks
        npc_dota_hero_muerta                                 = true,  -- 4 picks
        npc_dota_hero_monkey_king                            = true,  -- 4 picks
        npc_dota_hero_juggernaut                             = true,  -- 3 picks
        npc_dota_hero_ursa                                   = true,  -- 3 picks
        npc_dota_hero_abyssal_underlord                      = true,  -- 3 picks
        npc_dota_hero_doom_bringer                           = true,  -- 3 picks
        npc_dota_hero_gyrocopter                             = true,  -- 3 picks
    },
    [2] = {  -- Mids
        npc_dota_hero_ember_spirit                           = true,  -- 13 picks
        npc_dota_hero_queenofpain                            = true,  -- 12 picks
        npc_dota_hero_puck                                   = true,  -- 9 picks
        npc_dota_hero_pangolier                              = true,  -- 8 picks
        npc_dota_hero_sniper                                 = true,  -- 7 picks
        npc_dota_hero_void_spirit                            = true,  -- 7 picks
        npc_dota_hero_storm_spirit                           = true,  -- 6 picks
        npc_dota_hero_beastmaster                            = true,  -- 4 picks
        npc_dota_hero_sand_king                              = true,  -- 4 picks
        npc_dota_hero_kunkka                                 = true,  -- 3 picks
        npc_dota_hero_furion                                 = true,  -- 3 picks
        npc_dota_hero_huskar                                 = true,  -- 3 picks
    },
    [3] = {  -- Offlaners (tanks/initiators)
        npc_dota_hero_tidehunter                             = true,  -- 12 picks
        npc_dota_hero_bristleback                            = true,  -- 8 picks
        npc_dota_hero_doom_bringer                           = true,  -- 8 picks
        npc_dota_hero_abyssal_underlord                      = true,  -- 7 picks
        npc_dota_hero_beastmaster                            = true,  -- 6 picks
        npc_dota_hero_pangolier                              = true,  -- 6 picks
        npc_dota_hero_slardar                                = true,  -- 5 picks
        npc_dota_hero_mars                                   = true,  -- 5 picks
        npc_dota_hero_dawnbreaker                            = true,  -- 5 picks
        npc_dota_hero_ogre_magi                              = true,  -- 4 picks
        npc_dota_hero_alchemist                              = true,  -- 3 picks
        npc_dota_hero_nevermore                              = true,  -- 3 picks
    },
    [4] = {  -- Soft supports
        npc_dota_hero_rubick                                 = true,  -- 19 picks
        npc_dota_hero_phoenix                                = true,  -- 14 picks
        npc_dota_hero_lion                                   = true,  -- 6 picks
        npc_dota_hero_hoodwink                               = true,  -- 6 picks
        npc_dota_hero_shadow_demon                           = true,  -- 5 picks
        npc_dota_hero_grimstroke                             = true,  -- 5 picks
        npc_dota_hero_ogre_magi                              = true,  -- 5 picks
        npc_dota_hero_spirit_breaker                         = true,  -- 4 picks
        npc_dota_hero_lich                                   = true,  -- 4 picks
        npc_dota_hero_disruptor                              = true,  -- 3 picks
        npc_dota_hero_dark_willow                            = true,  -- 3 picks
        npc_dota_hero_keeper_of_the_light                    = true,  -- 3 picks
    },
    [5] = {  -- Hard supports
        npc_dota_hero_tusk                                   = true,  -- 11 picks
        npc_dota_hero_jakiro                                 = true,  -- 10 picks
        npc_dota_hero_rubick                                 = true,  -- 8 picks
        npc_dota_hero_hoodwink                               = true,  -- 8 picks
        npc_dota_hero_disruptor                              = true,  -- 7 picks
        npc_dota_hero_pudge                                  = true,  -- 5 picks
        npc_dota_hero_rattletrap                             = true,  -- 5 picks
        npc_dota_hero_skywrath_mage                          = true,  -- 5 picks
        npc_dota_hero_ogre_magi                              = true,  -- 4 picks
        npc_dota_hero_lion                                   = true,  -- 4 picks
        npc_dota_hero_grimstroke                             = true,  -- 4 picks
        npc_dota_hero_zuus                                   = true,  -- 4 picks
    },
}

function M.GetProPickBonus(cand, posIndex)
    if posIndex and M.PRO_PICKS_BY_POS[posIndex]
    and M.PRO_PICKS_BY_POS[posIndex][cand] then
        return 2.0
    end
    return 0
end

return M