"""
fetch_pro_picks.py — Generate PRO_PICKS_BY_POS from OpenDota pro match data.

Usage:
    pip install requests
    python tools/fetch_pro_picks.py

Output:
    Writes bots/FunLib/pro_picks_data.lua for automatic loading by draft_style.lua.

Position assignment uses net worth ranking (standard Dota analysis method):
  - lane=2, not roaming → pos2 (mid) — most reliable signal
  - is_roaming=true     → pos5 (hard support roamer)
  - remaining by NW desc → pos1 (carry), pos3 (offlaner), pos4, pos5
"""

import requests
import time
from collections import defaultdict

BASE_URL = "https://api.opendota.com/api"
MATCH_SAMPLE = 60
MIN_PICKS = 2
TOP_N = 12

POS_NAMES = {
    1: "Carries (safe lane)",
    2: "Mids",
    3: "Offlaners (tanks/initiators)",
    4: "Soft supports",
    5: "Hard supports",
}


def get(endpoint, retries=3):
    url = BASE_URL + endpoint
    for attempt in range(retries):
        try:
            r = requests.get(url, timeout=15)
            if r.status_code == 429:
                print("  [rate limit] sleeping 12s...")
                time.sleep(12)
                continue
            if r.status_code == 200:
                return r.json()
            print(f"  [warn] {r.status_code} {url}")
        except Exception as e:
            print(f"  [error] {e}")
        time.sleep(1.5 * (attempt + 1))
    return None


def fetch_hero_map():
    """Returns {hero_id: 'npc_dota_hero_xxx'}."""
    print("Fetching hero list...")
    heroes = get("/heroes")
    if not heroes:
        raise RuntimeError("Failed to fetch hero list")
    return {h["id"]: h["name"] for h in heroes}


def fetch_pro_match_ids(limit=MATCH_SAMPLE):
    print(f"Fetching {limit} recent pro matches...")
    data = get("/proMatches")
    if not data:
        raise RuntimeError("Failed to fetch pro matches")
    return [m["match_id"] for m in data[:limit]]


def assign_positions(team_players, hero_map):
    """
    Assign positions 1-5 per team using:
      1. lane=2 (mid lane) + highest NW  → pos2
      2. is_roaming=True  + lowest NW   → pos5
      3. Remaining sorted by NW desc    → pos1, pos3, pos4 (fill gaps)
    Returns list of (pos, hero_npc_name).
    """
    valid = [p for p in team_players if hero_map.get(p.get("hero_id"))]
    if not valid:
        return []

    result = []
    assigned = set()

    # --- pos2: mid lane ---
    mids = [p for p in valid if p.get("lane") == 2 and not p.get("is_roaming")]
    if mids:
        p = max(mids, key=lambda x: x.get("net_worth", 0))
        result.append((2, hero_map[p["hero_id"]]))
        assigned.add(p["hero_id"])

    # --- pos5: roaming support (lowest NW roamer) ---
    roamers = [p for p in valid if p.get("is_roaming") and p["hero_id"] not in assigned]
    if roamers:
        p = min(roamers, key=lambda x: x.get("net_worth", 0))
        result.append((5, hero_map[p["hero_id"]]))
        assigned.add(p["hero_id"])

    # --- remaining: pos1, pos3, pos4 (and pos5 if not found above) by NW desc ---
    used_pos = {pos for pos, _ in result}
    fill = [pos for pos in [1, 3, 4, 5] if pos not in used_pos]
    remaining = [p for p in valid if p["hero_id"] not in assigned]
    remaining.sort(key=lambda p: p.get("net_worth", 0), reverse=True)

    for i, pos in enumerate(fill):
        if i < len(remaining):
            result.append((pos, hero_map[remaining[i]["hero_id"]]))

    return result


def fetch_match_picks(match_id, hero_map):
    data = get(f"/matches/{match_id}")
    if not data or "players" not in data:
        return []

    players = data["players"]
    radiant = [p for p in players if p.get("player_slot", 0) < 128]
    dire    = [p for p in players if p.get("player_slot", 0) >= 128]

    picks = []
    for team in [radiant, dire]:
        picks.extend(assign_positions(team, hero_map))
    return picks


def build_counts(match_ids, hero_map):
    counts = defaultdict(lambda: defaultdict(int))
    total = len(match_ids)
    for i, mid in enumerate(match_ids):
        print(f"  [{i+1}/{total}] {mid}", end="\r")
        picks = fetch_match_picks(mid, hero_map)
        for pos, hero in picks:
            counts[pos][hero] += 1
        time.sleep(1.0)
    print()
    return counts


def top_heroes(counts, pos, n=TOP_N):
    heroes = {h: c for h, c in counts.get(pos, {}).items() if c >= MIN_PICKS}
    return sorted(heroes, key=lambda h: heroes[h], reverse=True)[:n]


def generate_lua(counts):
    lines = [
        "-- Auto-generated by tools/fetch_pro_picks.py",
        "-- Re-run the script to refresh with latest pro match data.",
        "",
        "local M = {}",
        "",
        "M.PRO_PICKS_BY_POS = {",
    ]
    for pos in range(1, 6):
        heroes = top_heroes(counts, pos)
        lines.append(f"    [{pos}] = {{  -- {POS_NAMES[pos]}")
        for hero in heroes:
            c = counts[pos][hero]
            lines.append(f"        {hero:<52} = true,  -- {c} picks")
        lines.append("    },")
    lines += [
        "}",
        "",
        "function M.GetProPickBonus(cand, posIndex)",
        "    if posIndex and M.PRO_PICKS_BY_POS[posIndex]",
        "    and M.PRO_PICKS_BY_POS[posIndex][cand] then",
        "        return 2.0",
        "    end",
        "    return 0",
        "end",
        "",
        "return M",
    ]
    return "\n".join(lines)


def print_summary(counts):
    print("\n=== Top picks by position ===")
    for pos in range(1, 6):
        print(f"\nPos {pos} — {POS_NAMES[pos]}:")
        for hero in top_heroes(counts, pos, n=10):
            short = hero.replace("npc_dota_hero_", "")
            print(f"  {short:<35} {counts[pos][hero]}")


def main():
    hero_map = fetch_hero_map()
    match_ids = fetch_pro_match_ids()

    print(f"\nFetching {len(match_ids)} match details (~{len(match_ids)}s)...")
    counts = build_counts(match_ids, hero_map)

    print_summary(counts)

    lua = generate_lua(counts)
    out = "bots/FunLib/pro_picks_data.lua"
    with open(out, "w", encoding="utf-8") as f:
        f.write(lua)
    print(f"\n[OK] Written to {out}")
    print("Restart Dota 2 to apply.")


if __name__ == "__main__":
    main()
